__all__ = ['INITIAL_REFERRAL_TOKENS', 'SECOND_LEVEL_REFERRAL_TOKENS', 'WALLET_PAY', 'LINK_BOT', 'DATABASE_PATH',
           'AUTHORIZATION_TOKEN', 'TON_API_URL', 'COMAND_STATISTINK', 'MANIFEST_URL', 'bot', 'dp', 'logger']

from .config import (
    INITIAL_REFERRAL_TOKENS,
    SECOND_LEVEL_REFERRAL_TOKENS,
    WALLET_PAY,
    LINK_BOT,
    DATABASE_PATH,
    AUTHORIZATION_TOKEN,
    TON_API_URL,
    COMAND_STATISTINK,
    MANIFEST_URL,
    bot,
    dp,
    logger
)
